# Generated by Django 5.2.6 on 2025-09-23 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('empl_fechacontrato', models.DateField(blank=True, null=True)),
                ('empl_cargo', models.CharField(blank=True, max_length=24, null=True)),
                ('empl_sueldo', models.IntegerField()),
            ],
            options={
                'db_table': 'EMPLEADO',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('espe_nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('espe_raza', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'ESPECIE',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('sed_nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('sed_region', models.CharField(blank=True, max_length=40, null=True)),
                ('sed_comuna', models.CharField(blank=True, max_length=40, null=True)),
                ('sed_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('sed_correo', models.EmailField(max_length=100, unique=True)),
                ('sed_numero', models.CharField(blank=True, max_length=15, null=True)),
                ('sed_capacidad', models.IntegerField()),
            ],
            options={
                'db_table': 'SEDE',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=40, null=True)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('user_nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('user_apellido', models.CharField(blank=True, max_length=40, null=True)),
                ('user_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('user_correo', models.EmailField(max_length=100, unique=True)),
                ('user_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('user_fechanac', models.DateField(blank=True, null=True)),
                ('user_fechareg', models.DateField(blank=True, null=True)),
                ('user_rol', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('masc_historial', models.CharField(blank=True, max_length=255, null=True)),
                ('masc_sexo', models.CharField(blank=True, max_length=15, null=True)),
                ('masc_edad', models.CharField(blank=True, max_length=3, null=True)),
                ('masc_nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('masc_descripcion', models.CharField(blank=True, max_length=40, null=True)),
                ('masc_fechaintroduccion', models.DateField(blank=True, null=True)),
                ('masc_estado', models.CharField(blank=True, max_length=40, null=True)),
                ('id_especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.especie')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.sede')),
            ],
            options={
                'db_table': 'MASCOTA',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('soli_descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('soli_fecha', models.DateField(blank=True, null=True)),
                ('soli_comision', models.IntegerField()),
                ('soli_estado', models.CharField(blank=True, max_length=40, null=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.empleado')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.mascota')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.sede')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.usuario')),
            ],
            options={
                'db_table': 'SOLICITUD',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.usuario'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id_post', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('post_categoria', models.CharField(max_length=50)),
                ('post_titulo', models.CharField(max_length=255)),
                ('contenido', models.CharField(max_length=255)),
                ('post_fecha', models.DateField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.usuario')),
            ],
            options={
                'db_table': 'BLOGPOST',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('visi_fecha', models.DateField(blank=True, null=True)),
                ('visi_Estado', models.CharField(blank=True, max_length=40, null=True)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.mascota')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.sede')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.usuario')),
            ],
            options={
                'db_table': 'VISITA',
            },
        ),
    ]
